---
name: MIME-Type-Simple
version: 0.01
author:
  - 'Robert Rothenberg <rrwo at cpan.org>'
abstract: MIME Media Types and their file extensions
license: perl
resources:
  license: ~
requires:
  Carp: 0
  Storable: 0
  Sub::Exporter: 0
build_requires:
  Test::More: 0
provides:
  DB:
    file: lib/MIME/Type/Simple.pm
  MIME::Type::Simple:
    file: lib/MIME/Type/Simple.pm
    version: 0.01
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
